<?php

Route::group([
    "prefix"=>"center",
],function(){
    Route::get('',"Web\WebController@center");
    Route::get('session',"Web\WebController@center");
    Route::get('init',"Web\WebController@center");
    Route::get('dashboard',"Web\WebController@center");
    Route::get('certify',"Web\WebController@center");
    Route::prefix('order')->group(function(){
        Route::get('list',"Web\WebController@center");
        Route::get('detail',"Web\WebController@center");
    });
    Route::prefix('product')->group(function(){
        Route::get('list',"Web\WebController@center");
        Route::get('edit',"Web\WebController@center");
        Route::get('add',"Web\WebController@center");
        Route::get('category',"Web\WebController@center");
    });
    Route::prefix('customer')->group(function(){
        Route::get('list',"Web\WebController@center");
    });
    Route::prefix('sale')->group(function(){
        Route::prefix('coupon')->group(function(){
            Route::get('list',"Web\WebController@center");
            Route::get('edit',"Web\WebController@center");
            Route::get('add',"Web\WebController@center");
        });
        Route::prefix('discount')->group(function(){
            Route::get('list',"Web\WebController@center");
            Route::get('edit',"Web\WebController@center");
            Route::get('add',"Web\WebController@center");
        });
        Route::prefix('match')->group(function(){
            Route::get('list',"Web\WebController@center");
            Route::get('edit',"Web\WebController@center");
            Route::get('add',"Web\WebController@center");
        });
    });
    Route::prefix('theme')->group(function(){
        Route::get('list',"Web\WebController@center");
        Route::get('setting',"Web\WebController@center");
    });
    Route::prefix('plugins')->group(function(){
        Route::get('list',"Web\WebController@center");
    });
    Route::get('image',"Web\WebController@center");
    Route::prefix('settings')->group(function(){
        Route::get('basic',"Web\WebController@center");
        Route::get('message',"Web\WebController@center");
        Route::get('payment',"Web\WebController@center");
        Route::get('shipment',"Web\WebController@center");
    });
    Route::prefix('user')->group(function(){
        Route::get('edit',"Web\WebController@center");
    });
});
