<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserWalletLogList extends Model
{
    const LOG_TYPE_IN = "in";
    const LOG_TYPE_OUT = "out";

    const logTypeMap = [
        self::LOG_TYPE_IN => "收入",
        self::LOG_TYPE_OUT => "支出"
    ];

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // 监听模型创建事件，在写入数据库之前触发
        static::creating(function ($model) {
            // 如果模型的 no 字段为空
            if (!$model->no) {
                // 调用 findAvailableNo 生成订单流水号
                $model->no = static::findAvailableNo();
                // 如果生成失败，则终止创建订单
                if (!$model->no) {
                    return false;
                }
            }
        });
    }

    public function wallet()
    {
        return $this->belongsTo(UserWallet::class,"wallet_id");
    }

    public static function findAvailableNo()
    {
        // 订单流水号前缀
        $prefix ="WA". date('YmdHis');
        for ($i = 0; $i < 10; $i++) {
            // 随机生成 6 位的数字
            $no = $prefix . str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);
            // 判断是否已经存在
            if (!static::query()->where('no', $no)->exists()) {
                return $no;
            }
        }
        return false;
    }
}
